name: myenv 
channels:  
  - anaconda  
  - conda-forge  
  - pytorch  
  - defaults  
dependencies:  
  - python=3.11.5  
  - tqdm==4.66.2
  - pandas=2.2.2
  - numpy=1.24.3
  - seaborn==0.13.2
  - matplotlib-base=3.8.4
  - rdkit=2023.03.3
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - transformers=4.37.2
  - scikit-learn=1.3.0
  - imbalanced-learn=0.12.2
  - xgboost=2.0.3
  - pip=23.3.1
  - pip:  
    - pubchempy=1.0.4
